project:
  name: "llm_sql_query_generator"
  version: "1.0.0"

model:
  name: "meta-llama/Meta-Llama-3-8B-Instruct"
  temperature: 0
  max_tokens: 200
  api_key: "${LLM_API_KEY}"

database:
  type: "sqlite"
  path: "data/database.sqlite"

evaluation:
  metrics: ["accuracy", "f1_score"]
  error_analysis: true

research:
  dataset_path: "data/raw/golden_dataset.csv"
  num_runs: 100

gold_test_set:
  path: "data/raw/gold-test-set.jsonl"

generated_output:
  path: "data/results/results.jsonl"
